Add PKT_KEEPALIVE, take udp host:port from PKT_CONNTEST2, reply something in SID_GETADVLISTEX
BNETDocs/Atlas pull request #13
Opened 2020-11-28 08:58 UTC by timfel

2020-11-28 09:37 UTC, carlbennett requested changes
Looks good so far. I'll wait to merge as I see there's still changes going on. Please review the items listed though in the meantime.

2020-11-28 09:37 UTC, carlbennett commented on src/Atlasd/Battlenet/Protocols/Game/Messages/SID_GETADVLISTEX.cs
> +                                w.Write(Encoding.UTF8.GetString(gameAd.Name));
These calls should be replaced with `w.WriteByteString(...)` instead.

2020-11-28 09:37 UTC, carlbennett commented on src/Atlasd/Battlenet/Protocols/UDP/UdpListener.cs
> +using Atlasd.Battlenet;
Minor nitpick for not alphabetizing this addition

2020-11-28 14:04 UTC, timfel commented on src/Atlasd/Battlenet/Protocols/Game/Messages/SID_GETADVLISTEX.cs
> +                                w.Write(Encoding.UTF8.GetString(gameAd.Name));
Fixed

2020-11-28 14:04 UTC, timfel commented on src/Atlasd/Battlenet/Protocols/UDP/UdpListener.cs
> +using Atlasd.Battlenet;
Fixed

2020-11-28 14:22 UTC, timfel commented
I've pushed a couple more minor edits, it's working now with the Stratagus engine same as pvpgn (i.e., create account, sign in, chat, create games, join games).

2020-11-29 08:29 UTC, carlbennett commented on src/Atlasd/Battlenet/Protocols/Game/Messages/SID_GETADVLISTEX.cs
> +                            foreach (var gameAd in gameAds)
Looping over the gameAds list isn't thread-safe. This may cause problems if a game is added or removed while this loop is processing. This is a systemic problem within Atlas, however.

2020-11-29 08:29 UTC, carlbennett commented on src/Atlasd/Battlenet/Protocols/UDP/UdpListener.cs
> +                            foreach(ClientState state in Battlenet.Common.ActiveClientStates)
`ClientState` could be `var` so that editing it or changing it later requires less code changes.

2020-11-29 08:29 UTC, carlbennett commented on src/Atlasd/Battlenet/Protocols/UDP/UdpListener.cs
> +                                        var ipEndPoint = remoteEndpoint as IPEndPoint;
Clever. :+1:

2020-11-30 13:45 UTC, timfel commented on src/Atlasd/Battlenet/Protocols/UDP/UdpListener.cs
> +                            foreach(ClientState state in Battlenet.Common.ActiveClientStates)
Done

2020-12-01 03:08 UTC, carlbennett commented on src/Atlasd/Battlenet/Protocols/Game/Messages/SID_GETADVLISTEX.cs
> +                            foreach (var gameAd in gameAds)
I've opened #14 to track this.

2020-12-01 03:08 UTC, carlbennett approved these changes

2020-12-01 03:08 UTC, merged